title: "PostGIS入門"
summary: "「PostGISを入れるところからやってみよう」を先にやってみることをお勧めします（リンク先は本書「はじめに」にあります）。"
topics: [PostGIS]
published: true
price: 0
# 一時的に設定
allow_override: true
# 本に含めるチャプターを順番に並べましょう
chapters:
  - introduction
  - geomtypes
  - srs
  - testing
  - editor
  - geog
  - geogfns
  - dump
  - collect
  - delcrack
  - within
  - conv-wkt-geom
  - conv-ewkt-geom
  - inpect-ewkt
  - conclusion
