title: "PostGIS入門"
summary: "「PostGISをはじめてみよう」を先にやってみることをお勧めします（リンク先は本書「はじめに」にあります）。"
topics: [PostGIS]
published: true
price: 0
# 一時的に設定
allow_override: true
# 本に含めるチャプターを順番に並べましょう
chapters:
  - introduction
  - geomtypes
  - srs
  - conv-ewkt-geom
  - testing
  - editor
  - measurement
  - geog
  - geogfns
  - spatial-index
  - dump
  - collect
  - delcrack
  - within
  - inpect-ewkt
  - conclusion
  - app-a-srs-cs
