title: "PostGISを入れるところからやってみよう"
summary: "ESRIシェープファイル形式のデータをPostGISに格納してQGISで表示するまでの手順を紹介しています。"
topics: [PostGIS]
published: true
price: 0
# 一時的に設定
allow_override: true
# 本に含めるチャプターを順番に並べましょう
chapters:
  - introduction.md
  - install-win.md
  - install-fbsd.md
  - create-table.md
  - import-cli.md
  - import-gui.md
  - import-ogr2ogr.md
  - qgis.md
  - qgis-wmts.md
  - conclusion.md
